# Generated by Django 2.2.7 on 2019-11-22 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=30)),
                ('account_options', models.CharField(choices=[('debit', 'DEBIT'), ('credit', 'CREDIT'), ('checking', 'CHECKING'), ('saving', 'SAVING')], default=('debit', 'DEBIT'), max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=30)),
                ('branch_location', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_options', models.CharField(choices=[('mortgage', 'MORTGAGE'), ('loan', 'LOAN'), ('leasing', 'LEASING'), ('treasury', 'TREASURY'), ('ach', 'ACH')], default=('mortgage', 'MORTGAGE'), max_length=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], default=('male', 'MALE'), max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Branch')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bank.Customer'),
        ),
    ]
